<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.54">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Aaron A. King">
<meta name="author" content="Edward L. Ionides">

<title>Lesson 6: Case study: polio – EpiSim</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>
MathJax = {
  loader: {
    load: ['[tex]/boldsymbol']
  },
  tex: {
    tags: "all",
    inlineMath: [['$','$'], ['\\(','\\)']],
    displayMath: [['$$','$$'], ['\\[','\\]']],
    processEscapes: true,
    processEnvironments: true,
    packages: {
      '[+]': ['boldsymbol']
    }
  }
};
</script>
<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">EpiSim</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../instruction.html"> 
<span class="menu-text">Instruction</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../introduction.html"> 
<span class="menu-text">Introduction</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../simulation.html"> 
<span class="menu-text">Simulation</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../likelihood.html"> 
<span class="menu-text">Likelihood</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../iterated.html"> 
<span class="menu-text">Maximum likelihood estimation and iterated filtering</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../metapop.html"> 
<span class="menu-text">Meta population modelling</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    <div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="main.pdf"><i class="bi bi-file-pdf"></i>Beamer</a></li><li><a href="main.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Lesson 6: Case study: polio</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Aaron A. King </p>
             <p>Edward L. Ionides </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"../_includes/setup.R"</span>, <span class="at">local =</span> knitr<span class="sc">::</span><span class="fu">knit_global</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="objectives" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="objectives">Objectives</h2>
<ol type="1">
<li><p>Demonstrate the use of covariates in pomp to add demographic data (birth rates and total population) and seasonality to an epidemiological model.</p></li>
<li><p>Show how partially observed Markov process (POMP) models and methods can be used to understand transmission dynamics of polio.</p></li>
<li><p>Practice maximizing the likelihood for such models. How to set up a global search for a maximum likelihood estimate. How to assess whether a search has been successful.</p></li>
<li><p>Provide a workflow that can be adapted to related data analysis tasks.</p></li>
</ol>
</section>
<section id="covariates" class="level1">
<h1>Covariates</h1>
<section id="reviewing-covariates-in-time-series-analysis" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="reviewing-covariates-in-time-series-analysis">Reviewing covariates in time series analysis</h2>
<ul>
<li><p>Suppose our time series of primary interest is <span class="math inline">\(y_{1:N}\)</span>.</p></li>
<li><p>A <em>covariate</em> time series is an additional time series <span class="math inline">\({z_{1:N}}\)</span> which is used to help explain <span class="math inline">\(y_{1:N}\)</span>.</p></li>
<li><p>When we talk about covariates, it is often implicit that we think of <span class="math inline">\({z_{1:N}}\)</span> as a measure of an <em>external forcing</em> to the system producing <span class="math inline">\(y_{1:N}\)</span>. This means that the process generating the data <span class="math inline">\({z_{1:N}}\)</span> affects the process generating <span class="math inline">\(y_{1:N}\)</span>, but not vice versa.</p></li>
<li><p>For example, the weather might affect human health, but human health has negligible effect on weather: weather is an external forcing to human health processes.</p></li>
<li><p>When the process leading to <span class="math inline">\({z_{1:N}}\)</span> is not external to the system generating it, we must be alert to the possibility of <em>reverse causation</em> and <em>confounding variables</em>.</p></li>
</ul>
</section>
<section id="including-covariates-in-the-general-pomp-framework" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="including-covariates-in-the-general-pomp-framework">Including covariates in the general POMP framework</h2>
<ul>
<li><p>The general POMP modeling framework allows essentially arbitrary modeling of covariates.</p></li>
<li><p>Recall that a POMP model is specified by defining, for <span class="math inline">\(n=1:N\)</span>, <span class="math display">\[\begin{array}{l}
    f_{X_{0}}(x_0\params\theta),
    \\
    f_{X_{n}|X_{n-1}}(x_{n}\given x_{n-1}\params\theta),
    \\
    f_{Y_{n}|X_n}(y_{n}\given x_n\params\theta).
  \end{array}\]</span></p></li>
<li><p>The possibility of a general dependence on <span class="math inline">\(n\)</span> includes the possibility that there is some covariate time series <span class="math inline">\(z_{0:N}\)</span> such that <span class="math display">\[\begin{array}{lcl}
    f_{X_{0}}(x_0\params\theta)&amp;=&amp; f_{X_{0}}(x_0\params\theta,z_0)
    \\
    f_{X_{n}|X_{n-1}}(x_{n}\given x_{n-1}\params\theta) &amp;=&amp; f_{X_{n}|X_{n-1}}(x_{n}\given x_{n-1}\params\theta,z_n),
    \\
    f_{Y_{n}|X_n}(y_{n}\given x_n\params\theta) &amp;=&amp; f_{Y_{n}|X_n}(y_{n}\given x_n\params\theta,z_n).
  \end{array}\]</span></p></li>
</ul>
</section>
<section id="seasonality-in-a-pomp-model" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="seasonality-in-a-pomp-model">Seasonality in a POMP model</h2>
<ul>
<li><p>One specific choice of covariates is to construct <span class="math inline">\(z_{0:N}\)</span> so that it fluctuates periodically, once per year. This allows <em>seasonality</em> enter the POMP model in whatever way is appropriate for the system under investigation.</p></li>
<li><p>All that remains is to hypothesize what is a reasonable way to include covariates for your system, and to fit the resulting model.</p></li>
<li><p>Now we can evaluate and maximize the log-likelihood, we can construct AIC or likelihood ratio tests to see if the covariate helps describe the data.</p></li>
<li><p>This also lets us compare alternative ways the covariates might enter the process model and/or the measurement model.</p></li>
</ul>
</section>
<section id="covariates-in-the-pomp-package" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="covariates-in-the-pomp-package">Covariates in the pomp package</h2>
<ul>
<li><p>pomp provides facilities for including covariates in a pomp object.</p></li>
<li><p>Named covariate time series entered via the <code>covar</code> argument to <code>pomp</code> are automatically defined within C snippets used for the <code>rprocess</code>, <code>dprocess</code>, <code>rmeasure</code>, <code>dmeasure</code> and <code>rinit</code> arguments.</p></li>
<li><p>We see this in practice in the following epidemiological model, which has population census, birth data and seasonality as covariates.</p></li>
</ul>
</section>
<section id="polio-in-wisconsin" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="polio-in-wisconsin">Polio in Wisconsin</h2>
<ul>
<li><p>The massive global polio eradication initiative (GPEI) has brought polio from a major global disease to the brink of extinction.</p></li>
<li><p>Finishing this task is proving hard, and improved understanding polio ecology might assist.</p></li>
<li><p><span class="citation" data-cites="Martinez-Bakker2015">Martinez-Bakker, King, and Rohani (<a href="#ref-Martinez-Bakker2015" role="doc-biblioref">2015</a>)</span> investigated this using extensive state level pre-vaccination era data in USA.</p></li>
<li><p>We will follow the approach of <span class="citation" data-cites="Martinez-Bakker2015">Martinez-Bakker, King, and Rohani (<a href="#ref-Martinez-Bakker2015" role="doc-biblioref">2015</a>)</span> for one state (Wisconsin). In the context of their model, we can quantify seasonality of transmission, the role of the birth rate in explaining the transmission dynamics, and the persistence mechanism of polio.</p></li>
</ul>
</section>
<section id="section" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="section"></h2>
<ul>
<li><span class="citation" data-cites="Martinez-Bakker2015">Martinez-Bakker, King, and Rohani (<a href="#ref-Martinez-Bakker2015" role="doc-biblioref">2015</a>)</span> carried out this analysis for all 48 contiguous states and District of Columbia, and their data and code are publicly available. The data we study, in <code>polio_wisconsin.csv</code>, consist of <code>cases</code>, the monthly reported polio cases; <code>births</code>, the monthly recorded births; <code>pop</code>, the annual census; <code>time</code>, date in years.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(tidyverse)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"https://kingaa.github.io/sbied/polio/polio_wisconsin.csv"</span>,</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">comment=</span><span class="st">"#"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(data,<span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 4
   time cases births     pop
  &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
1 1931.     7   4698 2990000
2 1931.     0   4354 2990000
3 1931.     7   4836 2990000
4 1931.     3   4468 2990000
5 1931.     4   4712 2990000</code></pre>
</div>
</div>
</section>
<section id="section-1" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="section-1"></h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="tmp//figure/data_plot-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%" data-fig-pos="h!"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="section-2" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="section-2"></h2>
<ul>
<li><p>We use the compartment model of <span class="citation" data-cites="Martinez-Bakker2015">Martinez-Bakker, King, and Rohani (<a href="#ref-Martinez-Bakker2015" role="doc-biblioref">2015</a>)</span>.</p></li>
<li><p>Compartments representing susceptible babies in each of six one-month birth cohorts (<span class="math inline">\(S^B_1\)</span>,…,<span class="math inline">\(S^B_6\)</span>), susceptible older individuals (<span class="math inline">\(S^O\)</span>), infected babies (<span class="math inline">\(I^B\)</span>), infected older individuals (<span class="math inline">\(I^O\)</span>), and recovered with lifelong immunity (<span class="math inline">\(R\)</span>).</p></li>
<li><p>The state vector of the disease transmission model consists of numbers of individuals in each compartment at each time, <span class="math display">\[X(t)=\big(S^B_1(t),...,S^B_6(t), I^B(t),I^O(t),R(t) \big).\]</span></p></li>
<li><p>Babies under six months are modeled as fully protected from symptomatic poliomyelitis.</p></li>
<li><p>Older infections lead to reported cases (usually paralysis) at a rate <span class="math inline">\(\rho\)</span>.</p></li>
<li><p>The flows through the compartments are graphically represented on the following slide (Figure 1A of <span class="citation" data-cites="Martinez-Bakker2015">Martinez-Bakker, King, and Rohani (<a href="#ref-Martinez-Bakker2015" role="doc-biblioref">2015</a>)</span>):</p></li>
</ul>
</section>
<section id="section-3" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="section-3"></h2>

</section>
<section id="section-4" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="section-4"></h2>
<p></p>
<ul>
<li><p>Duration of infection is comparable to the one-month reporting aggregation, so a discrete time model may be appropriate.</p></li>
<li><p><span class="citation" data-cites="Martinez-Bakker2015">Martinez-Bakker, King, and Rohani (<a href="#ref-Martinez-Bakker2015" role="doc-biblioref">2015</a>)</span> fitted monthly reported cases, May 1932 through January 1953, so we set <span class="math inline">\(t_n=1932+ (4+n)/12\)</span> and <span class="math display">\[X_n=X(t_n)=\big(S^B_{1,n},...,S^B_{6,n}, I^B_n,I^O_n,R_n \big).\]</span></p></li>
<li><p>The mean force of infection, in units of <span class="math inline">\(\mathrm{yr}^{-1}\)</span>, is modeled as <span class="math display">\[\bar\lambda_n=\left( \beta_n \frac{I^O_n+I^B_n}{P_n} + \psi \right)\]</span> where <span class="math inline">\(P_n\)</span> is census population interpolated to time <span class="math inline">\(t_n\)</span> and seasonality of transmission is modeled as <span class="math display">\[\beta_n=\exp\left\{ \sum_{k=1}^K b_k\xi_k(t_n) \right\},\]</span> with <span class="math inline">\(\{\xi_k(t),k=1,\dots,K\}\)</span> a periodic B-spline basis with <span class="math inline">\(K=6\)</span>.</p></li>
<li><p><span class="math inline">\(P_n\)</span> and <span class="math inline">\(\xi_k(t_n)\)</span> are <em>covariate time series</em>.</p></li>
</ul>
</section>
<section id="section-5" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="section-5"></h2>
<ul>
<li><p>The force of infection has a stochastic perturbation, <span class="math display">\[\lambda_n = \bar\lambda_n \epsilon_n,\]</span> where <span class="math inline">\(\epsilon_n\)</span> is a Gamma random variable with mean 1 and variance <span class="math inline">\(\sigma^2_{\mathrm{env}} + \sigma^2_{\mathrm{dem}}\big/\bar\lambda_n\)</span>. These two terms capture variation on the environmental and demographic scales, respectively. All compartments suffer a mortality rate, set at <span class="math inline">\(\delta=1/60\mathrm{yr}^{-1}\)</span>.</p></li>
<li><p>Within each month, all susceptible individuals are modeled as having exposure to constant competing hazards of mortality and polio infection. The chance of remaining in the susceptible population when exposed to these hazards for one month is therefore <span class="math display">\[p_n = \exp\big\{ -(\delta+\lambda_n)/12\big\},\]</span> with the chance of polio infection being <span class="math display">\[q_n = (1-p_n)\lambda_n\big/(\lambda_n+\delta).\]</span></p></li>
</ul>
</section>
<section id="section-6" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="section-6"></h2>
<ul>
<li>We employ a continuous population model, with no demographic stochasticity. Writing <span class="math inline">\(B_n\)</span> for births in month <span class="math inline">\(n\)</span>, we obtain the dynamic model of <span class="citation" data-cites="Martinez-Bakker2015">Martinez-Bakker, King, and Rohani (<a href="#ref-Martinez-Bakker2015" role="doc-biblioref">2015</a>)</span>: <span class="math display">\[\begin{array}{rcl}
    S^B_{1,n+1}&amp;=&amp;B_{n+1}\\
    S^B_{k,n+1}&amp;=&amp;p_nS^B_{k-1,n} \quad\mbox{for $k=2,\dots,6$}\\
    S^O_{n+1}&amp;=&amp; p_n(S^O_n+S^B_{6,n})\\
    I^B_{n+1}&amp;=&amp; q_n \sum_{k=1}^6 S^B_{k,n}\\
    I^O_{n+1}&amp;=&amp; q_n S^O_n
  \end{array}\]</span></li>
</ul>
</section>
<section id="the-measurement-model" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="the-measurement-model">The measurement model</h2>
<ul>
<li>The model for the reported observations, conditional on the state, is a discretized normal distribution truncated at zero, with both environmental and Poisson-scale contributions to the variance: <span class="math display">\[Y_n= \max\{\mathrm{round}(Z_n),0\}, \quad Z_n\sim\mathrm{normal}\left(\rho I^O_n, \big(\tau  I^O_n\big)^2 + \rho I^O_n\right).\]</span></li>
</ul>
</section>
<section id="initial-conditions" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="initial-conditions">Initial conditions</h2>
<p></p>
<ul>
<li><p>Additional parameters are used to specify initial state values at time <span class="math inline">\(t_0=1932+ 4/12\)</span>.</p></li>
<li><p>We will suppose there are parameters <span class="math inline">\(\big(\tilde S^B_{1,0},...,\tilde S^B_{6,0}, \tilde I^B_0,\tilde I^O_0,\tilde S^O_0\big)\)</span> that specify the population in each compartment at time <span class="math inline">\(t_0\)</span> via <span class="math display">\[ \hspace{-2mm} S^B_{1,0}= {\tilde S}^B_{1,0} ,...,S^B_{6,0}= \tilde S^B_{6,0}, \quad I^B_{0}= P_0 \tilde I^B_{0},\quad S^O_{0}= P_0 \tilde S^O_{0}, \quad I^O_{0}= P_0 \tilde I^O_{0}.\]</span></p></li>
<li><p>Following <span class="citation" data-cites="Martinez-Bakker2015">Martinez-Bakker, King, and Rohani (<a href="#ref-Martinez-Bakker2015" role="doc-biblioref">2015</a>)</span>, we make an approximation for the initial conditions of ignoring infant infections at time <span class="math inline">\(t_0\)</span>. Thus, we set <span class="math inline">\(\tilde I^B_{0}=0\)</span> and use monthly births in the preceding months (ignoring infant mortality) to fix <span class="math inline">\(\tilde S^B_{k,0}=B_{1-k}\)</span> for <span class="math inline">\(k=1,\dots,6\)</span>.</p></li>
<li><p>Estimated initial conditions are specified by <span class="math inline">\(\tilde I^O_{0}\)</span> and <span class="math inline">\(\tilde S^O_{0}\)</span>, since the initial recovered population, <span class="math inline">\(R_0\)</span>, is obtained by subtracting all other compartments from the total initial population, <span class="math inline">\(P_0\)</span>.</p></li>
<li><p>It is convenient to parameterize the estimated initial states as fractions of the population, whereas the initial states fixed at births are parameterized directly as a count.</p></li>
</ul>
</section>
</section>
<section id="a-representation-of-the-pomp-model" class="level1">
<h1>A representation of the POMP model</h1>
<section id="building-a-pomp-object-for-the-polio-model" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="building-a-pomp-object-for-the-polio-model">Building a <code>pomp</code> object for the polio model</h2>
<ul>
<li>We code the state variables, and the choice of <span class="math inline">\(t_0\)</span>, as</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>  statenames <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"SB1"</span>,<span class="st">"SB2"</span>,<span class="st">"SB3"</span>,<span class="st">"SB4"</span>,<span class="st">"SB5"</span>,<span class="st">"SB6"</span>,</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"IB"</span>,<span class="st">"SO"</span>,<span class="st">"IO"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  t0 <span class="ot">&lt;-</span> <span class="dv">1932</span><span class="sc">+</span><span class="dv">4</span><span class="sc">/</span><span class="dv">12</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>We do not explicitly code <span class="math inline">\(R\)</span>, since it is defined implicitly as the total population minus the sum of the other compartments. Due to lifelong immunity, individuals in <span class="math inline">\(R\)</span> play no role in the dynamics. Even occasional negative values of <span class="math inline">\(R\)</span> (due to a discrepancy between the census and the mortality model) would not be a fatal flaw.</li>
</ul>
</section>
<section id="setting-up-the-covariate-table" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="setting-up-the-covariate-table">Setting up the covariate table</h2>
<ul>
<li><code>time</code> gives the time at which the covariates are defined.</li>
<li><code>P</code> is a smoothed interpolation of the annual census.</li>
<li><code>B</code> is monthly births.</li>
<li><code>xi1,...,xi6</code> is a periodic B-spline basis</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(pomp)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  K <span class="ot">&lt;-</span> <span class="dv">6</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  covar <span class="ot">&lt;-</span> <span class="fu">covariate_table</span>(</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">t=</span>data<span class="sc">$</span>time,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">B=</span>data<span class="sc">$</span>births,</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">P=</span><span class="fu">predict</span>(</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">smooth.spline</span>(<span class="at">x=</span><span class="dv">1931</span><span class="sc">:</span><span class="dv">1954</span>,<span class="at">y=</span>data<span class="sc">$</span>pop[<span class="fu">seq</span>(<span class="dv">12</span>,<span class="dv">24</span><span class="sc">*</span><span class="dv">12</span>,<span class="at">by=</span><span class="dv">12</span>)]),</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>      <span class="at">x=</span>data<span class="sc">$</span>time)<span class="sc">$</span>y,</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">periodic_bspline_basis</span>(t,<span class="at">nbasis=</span>K,</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>      <span class="at">degree=</span><span class="dv">3</span>,<span class="at">period=</span><span class="dv">1</span>,<span class="at">names=</span><span class="st">"xi%d"</span>),</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">times=</span><span class="st">"t"</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="regular-parameters-and-initial-value-parameters" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="regular-parameters-and-initial-value-parameters">Regular parameters and initial value parameters</h2>
<ul>
<li>The parameters <span class="math inline">\(b_1,\dots,b_\mathrm{K},\psi,\rho,\tau,\sigma_\mathrm{dem}, \sigma_\mathrm{env}\)</span> in the model above are {regular parameters} (RPs), coded as</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>  rp_names <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"b1"</span>,<span class="st">"b2"</span>,<span class="st">"b3"</span>,<span class="st">"b4"</span>,<span class="st">"b5"</span>,<span class="st">"b6"</span>,</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"psi"</span>,<span class="st">"rho"</span>,<span class="st">"tau"</span>,<span class="st">"sigma_dem"</span>,<span class="st">"sigma_env"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>The {initial value parameters} (IVPs), <span class="math inline">\(\tilde I^O_{0}\)</span> and <span class="math inline">\(\tilde S^O_{0}\)</span>, are coded for each state named by adding <code>_0</code> to the state name:</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>  ivp_names <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"SO_0"</span>,<span class="st">"IO_0"</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  paramnames <span class="ot">&lt;-</span> <span class="fu">c</span>(rp_names,ivp_names)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="fixed-parameters-fps" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="fixed-parameters-fps">Fixed parameters (FPs)</h2>
<ul>
<li><p>Two quantities in the dynamic model specification, <span class="math inline">\(\delta=1/60 \mathrm{yr}^{-1}\)</span> and <span class="math inline">\(\mathrm{K}=6\)</span>, are not estimated.</p></li>
<li><p>Six other initial value quantities, <span class="math inline">\(\{\tilde S^B_{1,0},\dots,\tilde S^B_{6,0}\}\)</span>, are treated as fixed.</p></li>
<li><p>Fixed quantities could be coded as constants using the <code>globals</code> argument of <code>pomp</code>, but here we pass them as fixed parameters (FPs).</p></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>  fp_names <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"delta"</span>,<span class="st">"K"</span>,</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"SB1_0"</span>,<span class="st">"SB2_0"</span>,<span class="st">"SB3_0"</span>,<span class="st">"SB4_0"</span>,<span class="st">"SB5_0"</span>,<span class="st">"SB6_0"</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  paramnames <span class="ot">&lt;-</span> <span class="fu">c</span>(rp_names,ivp_names,fp_names)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  covar_index_t0 <span class="ot">&lt;-</span> <span class="fu">which</span>(<span class="fu">abs</span>(covar<span class="sc">@</span>times<span class="sc">-</span>t0)<span class="sc">&lt;</span><span class="fl">0.01</span>)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  initial_births <span class="ot">&lt;-</span> covar<span class="sc">@</span>table[<span class="st">"B"</span>,covar_index_t0<span class="dv">-0</span><span class="sc">:</span><span class="dv">5</span>]</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">names</span>(initial_births) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"SB1_0"</span>,<span class="st">"SB2_0"</span>,</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"SB3_0"</span>,<span class="st">"SB4_0"</span>,<span class="st">"SB5_0"</span>,<span class="st">"SB6_0"</span>)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  fixed_params <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">delta=</span><span class="dv">1</span><span class="sc">/</span><span class="dv">60</span>,<span class="at">K=</span>K,initial_births)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="a-starting-value-for-the-parameters" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="a-starting-value-for-the-parameters">A starting value for the parameters</h2>
<ul>
<li>We have to start somewhere for our search in parameter space.</li>
<li>The following parameter vector is based on informal model exploration and prior research:</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>  params_guess <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">b1=</span><span class="dv">3</span>,<span class="at">b2=</span><span class="dv">0</span>,<span class="at">b3=</span><span class="fl">1.5</span>,<span class="at">b4=</span><span class="dv">6</span>,<span class="at">b5=</span><span class="dv">5</span>,<span class="at">b6=</span><span class="dv">3</span>,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">psi=</span><span class="fl">0.002</span>,<span class="at">rho=</span><span class="fl">0.01</span>,<span class="at">tau=</span><span class="fl">0.001</span>,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">sigma_dem=</span><span class="fl">0.04</span>,<span class="at">sigma_env=</span><span class="fl">0.5</span>,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">SO_0=</span><span class="fl">0.12</span>,<span class="at">IO_0=</span><span class="fl">0.001</span>,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    fixed_params)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="section-7" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="section-7"></h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>  rprocess <span class="ot">&lt;-</span> <span class="fu">Csnippet</span>(<span class="st">"</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="st">    double beta = exp(dot_product( (int) K, &amp;xi1, &amp;b1));</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="st">    double lambda = (beta * (IO+IB) / P + psi);</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="st">    double var_epsilon = pow(sigma_dem,2)/ lambda +</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="st">      pow(sigma_env,2);</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="st">    lambda *= (var_epsilon &lt; 1.0e-6) ? 1 :</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="st">      rgamma(1/var_epsilon,var_epsilon);</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="st">    double p = exp(-(delta+lambda)/12);</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="st">    double q = (1-p)*lambda/(delta+lambda);</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="st">    SB1=B;</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a><span class="st">    SB2=SB1*p;</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="st">    SB3=SB2*p;</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a><span class="st">    SB4=SB3*p;</span></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a><span class="st">    SB5=SB4*p;</span></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a><span class="st">    SB6=SB5*p;</span></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a><span class="st">    SO=(SB6+SO)*p;</span></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a><span class="st">    IB=(SB1+SB2+SB3+SB4+SB5+SB6)*q;</span></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a><span class="st">    IO=SO*q;</span></span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a><span class="st">  "</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="section-8" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="section-8"></h2>
<p></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>  dmeasure <span class="ot">&lt;-</span> <span class="fu">Csnippet</span>(<span class="st">"</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="st">    double tol = 1.0e-25;</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="st">    double mean_cases = rho*IO;</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="st">    double sd_cases = sqrt(pow(tau*IO,2) + mean_cases);</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="st">    if(cases &gt; 0.0){</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="st">      lik = pnorm(cases+0.5,mean_cases,sd_cases,1,0)</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="st">        - pnorm(cases-0.5,mean_cases,sd_cases,1,0) + tol;</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="st">    } else{</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="st">      lik = pnorm(cases+0.5,mean_cases,sd_cases,1,0) + tol;</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="st">    }</span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="st">    if (give_log) lik = log(lik);"</span>)</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>  rmeasure <span class="ot">&lt;-</span> <span class="fu">Csnippet</span>(<span class="st">"</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a><span class="st">    cases = rnorm(rho*IO, sqrt( pow(tau*IO,2) + rho*IO ) );</span></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a><span class="st">    if (cases &gt; 0.0) {</span></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a><span class="st">      cases = nearbyint(cases);</span></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a><span class="st">    } else {</span></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a><span class="st">      cases = 0.0;</span></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a><span class="st">    }"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="section-9" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="section-9"></h2>
<p>The map from the initial value parameters to the initial value of the states at time <span class="math inline">\(t_0\)</span> is coded by the <code>rinit</code> function:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>  rinit <span class="ot">&lt;-</span> <span class="fu">Csnippet</span>(<span class="st">"</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="st">    SB1 = SB1_0;</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="st">    SB2 = SB2_0;</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="st">    SB3 = SB3_0;</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="st">    SB4 = SB4_0;</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="st">    SB5 = SB5_0;</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="st">    SB6 = SB6_0;</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="st">    IB = 0;</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a><span class="st">    IO = IO_0 * P;</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="st">    SO = SO_0 * P;</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a><span class="st">  "</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="parameter-transformations" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="parameter-transformations">Parameter transformations</h2>
<ul>
<li>For parameter estimation, it is helpful to have transformations that map each parameter into the whole real line and which put uncertainty close to a unit scale</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>  partrans <span class="ot">&lt;-</span> <span class="fu">parameter_trans</span>(</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">log=</span><span class="fu">c</span>(<span class="st">"psi"</span>,<span class="st">"rho"</span>,<span class="st">"tau"</span>,<span class="st">"sigma_dem"</span>,<span class="st">"sigma_env"</span>),</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">logit=</span><span class="fu">c</span>(<span class="st">"SO_0"</span>,<span class="st">"IO_0"</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>Since the seasonal splines are exponentiated, the <code>beta</code> parameters are already defined on the real line with unit scale uncertainty.</li>
</ul>
</section>
<section id="section-10" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="section-10"></h2>
<p>We now put these pieces together into a pomp object.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>  data <span class="sc">|&gt;</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>      time <span class="sc">&gt;</span> t0 <span class="sc">+</span> <span class="fl">0.01</span>,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>      time <span class="sc">&lt;</span> <span class="dv">1953</span><span class="sc">+</span><span class="dv">1</span><span class="sc">/</span><span class="dv">12</span><span class="fl">+0.01</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">|&gt;</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(cases,time) <span class="sc">|&gt;</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pomp</span>(</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>      <span class="at">times=</span><span class="st">"time"</span>,<span class="at">t0=</span>t0,</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>      <span class="at">params=</span>params_guess,</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>      <span class="at">rprocess=</span><span class="fu">euler</span>(<span class="at">step.fun=</span>rprocess,<span class="at">delta.t=</span><span class="dv">1</span><span class="sc">/</span><span class="dv">12</span>),</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>      <span class="at">rmeasure=</span>rmeasure,</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>      <span class="at">dmeasure=</span>dmeasure,</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>      <span class="at">rinit=</span>rinit,</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>      <span class="at">partrans=</span>partrans,</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>      <span class="at">covar=</span>covar,</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>      <span class="at">statenames=</span>statenames,</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>      <span class="at">paramnames=</span>paramnames</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>    ) <span class="ot">-&gt;</span> polio</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="logistics-for-the-computations" class="level1">
<h1>Logistics for the computations</h1>
</section>
<section id="controlling-run-time" class="level1">
<h1>Controlling run time</h1>
<section id="setting-run-levels-to-control-computation-time" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="setting-run-levels-to-control-computation-time">Setting run levels to control computation time</h2>
<ul>
<li><p><code>run_level=1</code> will set all the algorithmic parameters to the first column of values in the following code, for debugging.</p></li>
<li><p>Here, <code>Np</code> is the number of particles, <code>Nmif</code> is the number of iterations of the optimization procedure carried, other variables are defined for use later.</p></li>
<li><p><code>run_level=2</code> uses enough effort to gives reasonably stable results at a moderate computational time.</p></li>
<li><p>Larger values give more refined computations, implemented here by <code>run_level=3</code> which was run on a computing cluster.</p></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>  run_level <span class="ot">&lt;-</span> <span class="dv">3</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>  Np <span class="ot">&lt;-</span>          <span class="cf">switch</span>(run_level,<span class="dv">100</span>, <span class="fl">1e3</span>, <span class="fl">5e3</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  Nmif <span class="ot">&lt;-</span>        <span class="cf">switch</span>(run_level, <span class="dv">10</span>, <span class="dv">100</span>, <span class="dv">200</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  Nreps_eval <span class="ot">&lt;-</span>  <span class="cf">switch</span>(run_level,  <span class="dv">2</span>,  <span class="dv">10</span>,  <span class="dv">20</span>)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  Nreps_local <span class="ot">&lt;-</span> <span class="cf">switch</span>(run_level, <span class="dv">10</span>,  <span class="dv">20</span>,  <span class="dv">40</span>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  Nreps_global <span class="ot">&lt;-</span><span class="cf">switch</span>(run_level, <span class="dv">10</span>,  <span class="dv">20</span>, <span class="dv">100</span>)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  Nsim <span class="ot">&lt;-</span>        <span class="cf">switch</span>(run_level, <span class="dv">50</span>, <span class="dv">100</span>, <span class="dv">500</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="comments-on-setting-algorithmic-parameters" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="comments-on-setting-algorithmic-parameters">Comments on setting algorithmic parameters</h2>
<ul>
<li><p>Using <code>run_level</code> settings is convenient for editing source code. It plays no fundamental role in the final results. If you are not editing the source code, or using the code as a template for developing your own analysis, it has no function.</p></li>
<li><p>When you edit a document with different <code>run_level</code> options, you can debug your code by editing <code>run_level=1</code>. Then, you can get preliminary assessment of whether your results are sensible with <code>run_level=2</code> and get finalized results, with reduced Monte Carlo error, by editing <code>run_level=3</code>.</p></li>
<li><p>We intend <code>run_level=1</code> to run in minutes, <code>run_level=2</code> to run in tens of minutes, and <code>run_level=3</code> to run in hours.</p></li>
<li><p>You can increase or decrease the numbers of particles, or the number of mif2 iterations, or the number of global searches carried out, to make sure this procedure is practical on your machine.</p></li>
<li><p>Appropriate values of the algorithmic parameters for each run-level are context dependent.</p></li>
</ul>
</section>
<section id="choosing-algorithmic-parameters" class="level2">
<h2 class="anchored" data-anchor-id="choosing-algorithmic-parameters">Choosing algorithmic parameters</h2>
<p>Suppose you have selected a number of particles, <code>Np</code>, and number of iterated filtering iterations, <code>Nmif</code>, and number of Monte Carlo replications, <code>Reps</code>, that give a 10 minute maximization search using <code>mif2()</code>. Propose how you would adjust these to plan a more intensive search lasting about 2 hours.</p>
<p></p>
<p><a href="algorithmic-parameters-exercise.html">Worked solution to the Exercise</a></p>
</section>
<section id="setting-up-parallelization" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="setting-up-parallelization">Setting up parallelization</h2>
<p>We will use doFuture to parallelize our computations. At run-levels 1 and 2, it will be sufficient to use the multiple cores on a single machine, but at run-level 3, we will use an HPC cluster. In the following, we use our own HPC cluster. To run these codes on your own HPC cluster, you would need to edit the script suitably.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(doFuture)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(iterators)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  par_init <span class="ot">&lt;-</span> <span class="cf">function</span> (run_level) {</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (run_level <span class="sc">&gt;=</span> <span class="dv">3</span> <span class="sc">&amp;&amp;</span> <span class="fu">file.exists</span>(<span class="st">"CLUSTER.R"</span>)) {</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>      <span class="fu">source</span>(<span class="st">"CLUSTER.R"</span>)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>    } <span class="cf">else</span> {</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>      <span class="fu">plan</span>(multisession)</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>  }</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="parallel-computation-of-the-likelihood" class="level1">
<h1>Parallel computation of the likelihood</h1>
<section id="likelihood-evaluation-at-the-starting-parameter-estimate" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="likelihood-evaluation-at-the-starting-parameter-estimate">Likelihood evaluation at the starting parameter estimate</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stew</span>(<span class="at">file=</span><span class="st">"pf1.rda"</span>,<span class="at">seed=</span><span class="dv">3899882</span>,{</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">par_init</span>(run_level)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    pf1 <span class="ot">&lt;-</span> <span class="fu">foreach</span>(<span class="at">i=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>,<span class="at">.combine=</span>c,</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">.options.future=</span><span class="fu">list</span>(<span class="at">seed=</span><span class="cn">TRUE</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%dofuture%</span> <span class="fu">pfilter</span>(polio,<span class="at">Np=</span>Np)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    cores <span class="ot">&lt;-</span> <span class="fu">nbrOfWorkers</span>()</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  })</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  L1 <span class="ot">&lt;-</span> <span class="fu">logmeanexp</span>(<span class="fu">sapply</span>(pf1,logLik),<span class="at">se=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><p>In 55.7 seconds (with 250 cores) we obtain a log-likelihood estimate of -819.70 with a Monte Carlo standard error of 0.32.</p></li>
<li><p>Here, we use <code>stew()</code> to <em>cache</em> the results of the computation.</p></li>
</ul>
</section>
</section>
<section id="caching-results" class="level1">
<h1>Caching results</h1>
<section id="caching-computations-in-rmarkdown" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="caching-computations-in-rmarkdown">Caching computations in Rmarkdown</h2>
<ul>
<li><p>It is not unusual for computations in a POMP analysis to take hours to run on many cores.</p></li>
<li><p>The computations for a final version of a manuscript may take days.</p></li>
<li><p>Usually, we use some mechanism like the different values of <code>run_level</code> so that preliminary versions of the manuscript take less time to run.</p></li>
<li><p>However, when editing the text or working on a different part of the manuscript, we don’t want to re-run long pieces of code.</p></li>
<li><p>Saving results so that the code is only re-run when necessary is called <em>caching</em>.</p></li>
</ul>
</section>
<section id="section-11" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="section-11"></h2>
<ul>
<li><p>You may already be familiar the versions of caching provided in {.Rmd} and {.Rnw} files. The argument <code>cache=TRUE</code> can be set individually for each chunk or as a global option.</p></li>
<li><p>When <code>cache=TRUE</code>, Rmarkdown/knitr caches the results of the chunk, meaning that a chunk will only be re-run if code in that chunk is edited.</p></li>
<li><p>You can force Rmarkdown/knitr to recompute all the chunks by deleting the <code>cache</code> subdirectory.</p></li>
</ul>
</section>
<section id="practical-advice-for-caching" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="practical-advice-for-caching">Practical advice for caching</h2>
<ul>
<li><p>What if changes elsewhere in the document affect the proper evaluation of your chunk, but you didn’t edit any of the code in the chunk itself? Rmarkdown/knitr will get this wrong. <em>It will not recompute the chunk</em>.</p></li>
<li><p>A perfect caching system doesn’t exist. <em>Always delete the entire cache and rebuild a fresh cache before finishing a manuscript.</em></p></li>
<li><p>Rmarkdown/knitr caching is good for relatively small computations, such as producing figures or things that may take a minute or two and are annoying if you have to recompute them every time you make any edits to the text.</p></li>
<li><p>For longer computations, it is good to have full manual control. In pomp, this is provided by two related functions, <code>stew</code> and <code>bake</code>.</p></li>
</ul>
</section>
<section id="stew-and-bake" class="level2">
<h2 class="anchored" data-anchor-id="stew-and-bake"><code>stew</code> and <code>bake</code></h2>
<ul>
<li><p>Notice the function <code>stew</code> in the replicated particle filter code above.</p></li>
<li><p>Here, <code>stew</code> looks for a file called <code>pf1.rda</code>.</p></li>
<li><p>If it finds this file, it simply loads the contents of this file.</p></li>
<li><p>If the file doesn’t exist, it carries out the specified computation and saves it in a file of this name.</p></li>
<li><p><code>bake</code> is similar to <code>stew</code>. The difference is that <code>bake</code> uses <code>readRDS</code> and <code>saveRDS</code>, whereas <code>stew</code> uses <code>load</code> and <code>save</code>.</p></li>
<li><p>either way, the computation will not be re-run unless you edit the code, change something on which the computation depends, or manually delete the archive file (<code>pf1.rda</code>).</p></li>
<li><p><code>stew</code> and <code>bake</code> reset the seed appropriately whether or not the computation is recomputed. Otherwise, caching risks adverse consequences for reproducibility.</p></li>
</ul>
</section>
</section>
<section id="persistence-of-polio" class="level1">
<h1>Persistence of polio</h1>
<section id="simulation-to-investigate-local-persistence" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="simulation-to-investigate-local-persistence">Simulation to investigate local persistence</h2>
<ul>
<li>The scientific purpose of fitting a model typically involves analyzing properties of the fitted model, often investigated using simulation.</li>
<li>Following <span class="citation" data-cites="Martinez-Bakker2015">Martinez-Bakker, King, and Rohani (<a href="#ref-Martinez-Bakker2015" role="doc-biblioref">2015</a>)</span>, we are interested in how often months with no reported cases (<span class="math inline">\(Y_n=0\)</span>) correspond to months without any local asymptomatic cases, defined for our continuous state model as <span class="math inline">\(I^B_n+I^O_n&lt;1/2\)</span>.</li>
<li>For Wisconsin, using our model at the estimated MLE, we simulate in parallel as follows:</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">simulate</span>(polio,<span class="at">nsim=</span>Nsim,<span class="at">seed=</span><span class="dv">1643079359</span>,</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">format=</span><span class="st">"data.frame"</span>,<span class="at">include.data=</span><span class="cn">TRUE</span>) <span class="ot">-&gt;</span> sims</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="section-12" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="section-12"></h2>
<p>For the data, there were 26 months with no reported cases, similar to the mean of 51.7 for simulations from the fitted model.</p>
<p>Months with no asymptomatic infections for the simulations were rare, on average 0.80 months per simulation.</p>
<p>Months with fewer than 100 infections averaged 65 per simulation, which in the context of a reporting rate of 0.0100 can explain the absences of case reports.</p>
<p>The mean monthly infections due to importations, modeled by <span class="math inline">\(\psi\)</span>, is 120. This does not give much opportunity for local elimination of poliovirus.</p>
</section>
<section id="section-13" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="section-13"></h2>
<ul>
<li>It is also good practice to look at simulations from the fitted model:</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>  mle_simulation <span class="ot">&lt;-</span> <span class="fu">simulate</span>(polio,<span class="at">seed=</span><span class="dv">902683441</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(mle_simulation)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="tmp//figure/plot_simulated-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-fig-pos="h!" width="2049"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="section-14" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="section-14"></h2>
<ul>
<li><p>We see from this simulation that the fitted model can generate report histories that look qualitatively similar to the data. However, there are things to notice in the reconstructed latent states. Specifically, the pool of older susceptibles, <span class="math inline">\(S^O(t)\)</span>, is mostly increasing. The reduced case burden in the data in the time interval 1932–1945 is explained by a large initial recovered (<span class="math inline">\(R\)</span>) population, which implies much higher levels of polio before 1932. There were large epidemics of polio in the USA early in the 20th century, so this is not implausible.</p></li>
<li><p>A likelihood profile over the parameter <span class="math inline">\(\tilde S^O_0\)</span> could help to clarify to what extent this is a critical feature of how the model explains the data.</p></li>
</ul>
</section>
</section>
<section id="likelihood-maximization" class="level1">
<h1>Likelihood maximization</h1>
<section id="local-likelihood-maximization" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="local-likelihood-maximization">Local likelihood maximization</h2>
<ul>
<li>Let’s see if we can improve on the previous MLE. We use the IF2 algorithm. We set a constant random walk standard deviation for each of the regular parameters and a larger constant for each of the initial value parameters:</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>  mif.rw.sd <span class="ot">&lt;-</span> <span class="fu">eval</span>(<span class="fu">substitute</span>(<span class="fu">rw_sd</span>(</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">b1=</span>rwr,<span class="at">b2=</span>rwr,<span class="at">b3=</span>rwr,<span class="at">b4=</span>rwr,<span class="at">b5=</span>rwr,<span class="at">b6=</span>rwr,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">psi=</span>rwr,<span class="at">rho=</span>rwr,<span class="at">tau=</span>rwr,<span class="at">sigma_dem=</span>rwr,</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">sigma_env=</span>rwr,</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">IO_0=</span><span class="fu">ivp</span>(rwi),<span class="at">SO_0=</span><span class="fu">ivp</span>(rwi)),</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">list</span>(<span class="at">rwi=</span><span class="fl">0.2</span>,<span class="at">rwr=</span><span class="fl">0.02</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="section-15" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="section-15"></h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stew</span>(<span class="at">file=</span><span class="st">"mif.rda"</span>,<span class="at">seed=</span><span class="dv">942098028</span>,{</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">par_init</span>(run_level)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    m2 <span class="ot">&lt;-</span> <span class="fu">foreach</span>(</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">i=</span><span class="dv">1</span><span class="sc">:</span>Nreps_local,<span class="at">.combine=</span>c,</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">.options.future=</span><span class="fu">list</span>(<span class="at">seed=</span><span class="cn">TRUE</span>)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%dofuture%</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">mif2</span>(polio, <span class="at">Np=</span>Np, <span class="at">Nmif=</span>Nmif, <span class="at">rw.sd=</span>mif.rw.sd,</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">cooling.fraction.50=</span><span class="fl">0.5</span>)</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>    lik_m2 <span class="ot">&lt;-</span> <span class="fu">foreach</span>(</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>      <span class="at">m=</span>m2,<span class="at">.combine=</span>rbind,</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>      <span class="at">.options.future=</span><span class="fu">list</span>(<span class="at">seed=</span><span class="cn">TRUE</span>)</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%dofuture%</span></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>      <span class="fu">logmeanexp</span>(<span class="fu">replicate</span>(Nreps_eval,</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>        <span class="fu">logLik</span>(<span class="fu">pfilter</span>(m,<span class="at">Np=</span>Np))),<span class="at">se=</span><span class="cn">TRUE</span>)</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>  })</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coef</span>(m2) <span class="sc">|&gt;</span> <span class="fu">melt</span>() <span class="sc">|&gt;</span> <span class="fu">spread</span>(name,value) <span class="sc">|&gt;</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(<span class="sc">-</span>.id) <span class="sc">|&gt;</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">bind_cols</span>(<span class="at">logLik=</span>lik_m2[,<span class="dv">1</span>],<span class="at">logLik_se=</span>lik_m2[,<span class="dv">2</span>]) <span class="ot">-&gt;</span> r2</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  r2 <span class="sc">|&gt;</span> <span class="fu">arrange</span>(<span class="sc">-</span>logLik) <span class="sc">|&gt;</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">write_csv</span>(<span class="st">"params.csv"</span>)</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>(r2<span class="sc">$</span>logLik,<span class="at">digits=</span><span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 -797.1  -796.0  -795.5  -795.6  -795.2  -794.9 </code></pre>
</div>
</div>
<ul>
<li>This investigation took 14.6~min.</li>
<li>These repeated stochastic maximizations can also show us the geometry of the likelihood surface in a neighborhood of this point estimate:</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pairs</span>(<span class="sc">~</span>logLik<span class="sc">+</span>psi<span class="sc">+</span>rho<span class="sc">+</span>tau<span class="sc">+</span>sigma_dem<span class="sc">+</span>sigma_env,</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">data=</span><span class="fu">subset</span>(r2,logLik<span class="sc">&gt;</span><span class="fu">max</span>(logLik)<span class="sc">-</span><span class="dv">20</span>),<span class="at">pch=</span><span class="dv">16</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="tmp//figure/pairs-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-fig-pos="h!" width="2049"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>We see strong tradeoffs between <span class="math inline">\(\psi\)</span>, <span class="math inline">\(\rho\)</span> and <span class="math inline">\(\sigma_\mathrm{dem}\)</span>. By itself, in the absence of other assumptions, the pathogen immigration rate <span class="math inline">\(\psi\)</span> is fairly weakly identified. However, the reporting rate <span class="math inline">\(\rho\)</span> is essentially the fraction of poliovirus infections leading to acute flaccid paralysis, which is known to be around 1%. This plot suggests that fixing an assumed value of <span class="math inline">\(\rho\)</span> might lead to much more precise inference on <span class="math inline">\(\psi\)</span>; the rate of pathogen immigration presumably being important for understanding disease persistence. These hypotheses could be investigated more formally by construction of profile likelihood plots and likelihood ratio tests.</li>
</ul>
</section>
<section id="global-likelihood-maximization" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="global-likelihood-maximization">Global likelihood maximization</h2>
<ul>
<li><p>Practical parameter estimation involves trying many starting values for the parameters. One can specify a large box in parameter space that contains all sensible parameter vectors.</p></li>
<li><p>If the estimation gives stable conclusions with starting values drawn randomly from this box, we have some confidence that our global search is reliable.</p></li>
<li><p>For our polio model, a reasonable box might be:</p></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>  box <span class="ot">&lt;-</span> <span class="fu">rbind</span>(</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">b1=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">2</span>,<span class="dv">8</span>), <span class="at">b2=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">2</span>,<span class="dv">8</span>),</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">b3=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">2</span>,<span class="dv">8</span>), <span class="at">b4=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">2</span>,<span class="dv">8</span>),</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">b5=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">2</span>,<span class="dv">8</span>), <span class="at">b6=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">2</span>,<span class="dv">8</span>),</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">psi=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">0.1</span>), <span class="at">rho=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">0.1</span>), <span class="at">tau=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">0.1</span>),</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">sigma_dem=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">0.5</span>), <span class="at">sigma_env=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>),</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">SO_0=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">IO_0=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">0.01</span>)</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We then carry out a search identical to the local one except for the starting parameter values. This can be succinctly coded by calling <code>mif2</code> on the previously constructed object, <code>m2[[1]]</code>, with a reset starting value:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bake</span>(<span class="at">file=</span><span class="st">"box_eval1.rds"</span>,<span class="at">seed=</span><span class="dv">833102018</span>,{</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">par_init</span>(run_level)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">foreach</span>(<span class="at">i=</span><span class="dv">1</span><span class="sc">:</span>Nreps_global,<span class="at">.combine=</span>c,</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">.options.future=</span><span class="fu">list</span>(<span class="at">seed=</span><span class="cn">TRUE</span>)) <span class="sc">%dofuture%</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">mif2</span>(m2[[<span class="dv">1</span>]],<span class="at">params=</span><span class="fu">c</span>(fixed_params,</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>        <span class="fu">apply</span>(box,<span class="dv">1</span>,<span class="cf">function</span>(x)<span class="fu">runif</span>(<span class="dv">1</span>,x[<span class="dv">1</span>],x[<span class="dv">2</span>]))))</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  }) <span class="ot">-&gt;</span> m3</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bake</span>(<span class="at">file=</span><span class="st">"box_eval2.rds"</span>,<span class="at">seed=</span><span class="dv">71449038</span>,{</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">par_init</span>(run_level)</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">foreach</span>(<span class="at">m=</span>m3,<span class="at">.combine=</span>rbind,</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>      <span class="at">.options.future=</span><span class="fu">list</span>(<span class="at">seed=</span><span class="cn">TRUE</span>)) <span class="sc">%dofuture%</span></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>      <span class="fu">logmeanexp</span>(<span class="fu">replicate</span>(Nreps_eval,</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>        <span class="fu">logLik</span>(<span class="fu">pfilter</span>(m,<span class="at">Np=</span>Np))),<span class="at">se=</span><span class="cn">TRUE</span>)</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>  }) <span class="ot">-&gt;</span> lik_m3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coef</span>(m3) <span class="sc">|&gt;</span> <span class="fu">melt</span>() <span class="sc">|&gt;</span> <span class="fu">spread</span>(name,value) <span class="sc">|&gt;</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(<span class="sc">-</span>.id) <span class="sc">|&gt;</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">bind_cols</span>(<span class="at">logLik=</span>lik_m3[,<span class="dv">1</span>],<span class="at">logLik_se=</span>lik_m3[,<span class="dv">2</span>]) <span class="ot">-&gt;</span> r3</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">read_csv</span>(<span class="st">"params.csv"</span>) <span class="sc">|&gt;</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">bind_rows</span>(r3) <span class="sc">|&gt;</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(<span class="sc">-</span>logLik) <span class="sc">|&gt;</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">write_csv</span>(<span class="st">"params.csv"</span>)</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>(r3<span class="sc">$</span>logLik,<span class="at">digits=</span><span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 -913.6  -796.4  -795.7  -799.4  -795.3  -794.7 </code></pre>
</div>
</div>
<ul>
<li><p>Evaluation of the best result of this search gives a likelihood of -794.7 with a standard error of 0.1. We see that optimization attempts from diverse remote starting points can approach our MLE, but do not exceed it. This gives us some reasonable confidence in our MLE.</p></li>
<li><p>Plotting these diverse parameter estimates can help to give a feel for the global geometry of the likelihood surface</p></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pairs</span>(<span class="sc">~</span>logLik<span class="sc">+</span>psi<span class="sc">+</span>rho<span class="sc">+</span>tau<span class="sc">+</span>sigma_dem<span class="sc">+</span>sigma_env,</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">data=</span><span class="fu">subset</span>(r3,logLik<span class="sc">&gt;</span><span class="fu">max</span>(logLik)<span class="sc">-</span><span class="dv">20</span>),<span class="at">pch=</span><span class="dv">16</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="tmp//figure/pairs_global-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-fig-pos="h!" width="2049"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="benchmark-likelihoods-for-non-mechanistic-models" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="benchmark-likelihoods-for-non-mechanistic-models">Benchmark likelihoods for non-mechanistic models</h2>
<ul>
<li>To understand these global searches, many of which may correspond to parameter values having no meaningful scientific interpretation, it is helpful to put the log-likelihoods in the context of some non-mechanistic benchmarks.</li>
<li>The most basic statistical model for data is independent, identically distributed (IID). Picking a negative binomial model,</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>  nb_lik <span class="ot">&lt;-</span> <span class="cf">function</span> (theta) {</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>    <span class="sc">-</span><span class="fu">sum</span>(<span class="fu">dnbinom</span>(<span class="fu">as.numeric</span>(<span class="fu">obs</span>(polio)),</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">size=</span><span class="fu">exp</span>(theta[<span class="dv">1</span>]),<span class="at">prob=</span><span class="fu">exp</span>(theta[<span class="dv">2</span>]),<span class="at">log=</span><span class="cn">TRUE</span>))}</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  nb_mle <span class="ot">&lt;-</span> <span class="fu">optim</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="sc">-</span><span class="dv">5</span>),nb_lik)</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="sc">-</span>nb_mle<span class="sc">$</span>value</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1036.227</code></pre>
</div>
</div>
<ul>
<li>A model with likelihood below -1036.2 is unreasonable. This explains a cutoff around this value in the global searches: in these cases, the model is finding essentially IID explanations for the data.</li>
</ul>
</section>
<section id="arma-models-as-benchmarks" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="arma-models-as-benchmarks">ARMA models as benchmarks</h2>
<ul>
<li>Linear, Gaussian auto-regressive moving-average (ARMA) models provide non-mechanistic fits to the data including flexible dependence relationships.</li>
<li>We fit to <span class="math inline">\(\log(y_n^*+1)\)</span> and correct the likelihood back to the scale appropriate for the untransformed data:</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>  log_y <span class="ot">&lt;-</span> <span class="fu">log</span>(<span class="fu">as.vector</span>(<span class="fu">obs</span>(polio))<span class="sc">+</span><span class="dv">1</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  arma_fit <span class="ot">&lt;-</span> <span class="fu">arima</span>(log_y,<span class="at">order=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">0</span>,<span class="dv">2</span>),</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">seasonal=</span><span class="fu">list</span>(<span class="at">order=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>),<span class="at">period=</span><span class="dv">12</span>))</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  arma_fit<span class="sc">$</span>loglik<span class="sc">-</span><span class="fu">sum</span>(log_y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -822.0827</code></pre>
</div>
</div>
<ul>
<li>This 7-parameter model, which knows nothing of susceptible depletion, attains a likelihood of -822.1.</li>
<li>The aim of mechanistic modeling here is not to beat non-mechanistic models, but it is comforting that we’re competitive with them.</li>
</ul>
</section>
<section id="mining-previous-investigations-of-the-likelihood" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="mining-previous-investigations-of-the-likelihood">Mining previous investigations of the likelihood</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>  params <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"params.csv"</span>)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pairs</span>(<span class="sc">~</span>logLik<span class="sc">+</span>psi<span class="sc">+</span>rho<span class="sc">+</span>tau<span class="sc">+</span>sigma_dem<span class="sc">+</span>sigma_env,</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">data=</span><span class="fu">subset</span>(params,logLik<span class="sc">&gt;</span><span class="fu">max</span>(logLik)<span class="sc">-</span><span class="dv">20</span>),<span class="at">pch=</span><span class="dv">16</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="tmp//figure/param_file-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%" data-fig-pos="h!"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Here, we see that the most successful searches have always led to models with reporting rate around 1-2%. This impression can be reinforced by looking at results from the global searches:</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(logLik<span class="sc">~</span>rho,<span class="at">data=</span><span class="fu">subset</span>(r3,logLik<span class="sc">&gt;</span><span class="fu">max</span>(r3<span class="sc">$</span>logLik)<span class="sc">-</span><span class="dv">10</span>),<span class="at">log=</span><span class="st">"x"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="tmp//figure/global_rho_plot-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%" data-fig-pos="h!"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Reporting rates close to 1% provide a small but clear advantage (several units of log-likelihood) in explaining the data. For these reporting rates, depletion of susceptibles can help to explain the dynamics.</li>
</ul>
</section>
</section>
<section id="profile-likelihood" class="level1">
<h1>Profile likelihood</h1>
<section id="profile-likelihood-1" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="profile-likelihood-1">Profile likelihood</h2>
<ul>
<li>First, we must decide the ranges of parameter starting values for the searches.</li>
<li>We build a search box using the range of finishing values from previous searches.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(tidyverse)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  params <span class="sc">|&gt;</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(logLik<span class="sc">&gt;</span><span class="fu">max</span>(logLik)<span class="sc">-</span><span class="dv">20</span>) <span class="sc">|&gt;</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(<span class="sc">-</span>logLik,<span class="sc">-</span>logLik_se) <span class="sc">|&gt;</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">gather</span>(variable,value) <span class="sc">|&gt;</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(variable) <span class="sc">|&gt;</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">min=</span><span class="fu">min</span>(value),<span class="at">max=</span><span class="fu">max</span>(value)) <span class="sc">|&gt;</span></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ungroup</span>() <span class="sc">|&gt;</span></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">column_to_rownames</span>(<span class="at">var=</span><span class="st">"variable"</span>) <span class="sc">|&gt;</span></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">t</span>() <span class="ot">-&gt;</span> box</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>We must decide how many points to plot along the profile, and the number of Monte Carlo replicates at each point.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>  profile_pts <span class="ot">&lt;-</span>  <span class="cf">switch</span>(run_level,  <span class="dv">3</span>,  <span class="dv">5</span>,  <span class="dv">30</span>)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  profile_Nreps <span class="ot">&lt;-</span> <span class="cf">switch</span>(run_level, <span class="dv">2</span>,  <span class="dv">3</span>,  <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>We build a dataframe with a row setting up each profile search</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>  idx <span class="ot">&lt;-</span> <span class="fu">which</span>(<span class="fu">colnames</span>(box)<span class="sc">!=</span><span class="st">"rho"</span>)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">profile_design</span>(</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">rho=</span><span class="fu">seq</span>(<span class="fl">0.01</span>,<span class="fl">0.025</span>,<span class="at">length=</span>profile_pts),</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">lower=</span>box[<span class="st">"min"</span>,idx],<span class="at">upper=</span>box[<span class="st">"max"</span>,idx],</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">nprof=</span>profile_Nreps</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="ot">-&gt;</span> starts</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>Note that <span class="math inline">\(\rho\)</span> is not perturbed in the IF iterations for the purposes of the profile calculation.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>  profile.rw.sd <span class="ot">&lt;-</span> <span class="fu">eval</span>(<span class="fu">substitute</span>(<span class="fu">rw_sd</span>(</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">rho=</span><span class="dv">0</span>,<span class="at">b1=</span>rwr,<span class="at">b2=</span>rwr,<span class="at">b3=</span>rwr,<span class="at">b4=</span>rwr,<span class="at">b5=</span>rwr,<span class="at">b6=</span>rwr,</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">psi=</span>rwr,<span class="at">tau=</span>rwr,<span class="at">sigma_dem=</span>rwr,<span class="at">sigma_env=</span>rwr,</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">IO_0=</span><span class="fu">ivp</span>(rwi),<span class="at">SO_0=</span><span class="fu">ivp</span>(rwi)),</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">list</span>(<span class="at">rwi=</span><span class="fl">0.2</span>,<span class="at">rwr=</span><span class="fl">0.02</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>Otherwise, the following code to compute the profile is identical to a global search <span class="math inline">\(\dots\)</span></li>
<li>It took <span class="math inline">\(32.5\)</span> minutes to run on <span class="math inline">\(250\)</span> cores.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>    <span class="fu">stew</span>(<span class="at">file=</span><span class="st">"profile_rho.rda"</span>,<span class="at">seed=</span><span class="dv">1888257101</span>,{</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>      <span class="fu">par_init</span>(run_level)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>      <span class="fu">foreach</span>(<span class="at">start=</span><span class="fu">iter</span>(starts,<span class="st">"row"</span>),<span class="at">.combine=</span>rbind,</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">.options.future=</span><span class="fu">list</span>(<span class="at">seed=</span><span class="cn">TRUE</span>)) <span class="sc">%dofuture%</span> {</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>          polio <span class="sc">|&gt;</span> <span class="fu">mif2</span>(<span class="at">params=</span>start,</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">Np=</span>Np,<span class="at">Nmif=</span><span class="fu">ceiling</span>(Nmif<span class="sc">/</span><span class="dv">2</span>),</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">cooling.fraction.50=</span><span class="fl">0.5</span>,</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">rw.sd=</span>profile.rw.sd</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>          ) <span class="sc">|&gt;</span></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>            <span class="fu">mif2</span>(<span class="at">Np=</span>Np,<span class="at">Nmif=</span><span class="fu">ceiling</span>(Nmif<span class="sc">/</span><span class="dv">2</span>),</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>              <span class="at">cooling.fraction.50=</span><span class="fl">0.1</span></span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>            ) <span class="ot">-&gt;</span> mf</span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>          <span class="fu">replicate</span>(Nreps_eval,</span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a>            mf <span class="sc">|&gt;</span> <span class="fu">pfilter</span>(<span class="at">Np=</span>Np) <span class="sc">|&gt;</span> <span class="fu">logLik</span>()</span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a>          ) <span class="sc">|&gt;</span> <span class="fu">logmeanexp</span>(<span class="at">se=</span><span class="cn">TRUE</span>) <span class="ot">-&gt;</span> ll</span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a>          mf <span class="sc">|&gt;</span> <span class="fu">coef</span>() <span class="sc">|&gt;</span> <span class="fu">bind_rows</span>() <span class="sc">|&gt;</span></span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a>            <span class="fu">bind_cols</span>(<span class="at">logLik=</span>ll[<span class="dv">1</span>],<span class="at">logLik_se=</span>ll[<span class="dv">2</span>])</span>
<span id="cb41-18"><a href="#cb41-18" aria-hidden="true" tabindex="-1"></a>        } <span class="ot">-&gt;</span> m4</span>
<span id="cb41-19"><a href="#cb41-19" aria-hidden="true" tabindex="-1"></a>      cores <span class="ot">&lt;-</span> <span class="fu">nbrOfWorkers</span>()</span>
<span id="cb41-20"><a href="#cb41-20" aria-hidden="true" tabindex="-1"></a>    })</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="tmp//figure/profile_rho_plot1-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%" data-fig-pos="h!"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="exercises" class="level1">
<h1>Exercises</h1>
<section id="initial-values." class="level2">
<h2 class="anchored" data-anchor-id="initial-values.">Initial values.</h2>
<p>When carrying out parameter estimation for dynamic systems, we need to specify beginning values for both the dynamic system (in the state space) and the parameters (in the parameter space). By convention, we use <em>initial values</em> for the initialization of the dynamic system and <em>starting values</em> for initialization of the parameter search.</p>
<p>Discuss issues in specifying and inferring initial conditions, with particular reference to this polio example.</p>
<p>Suggest a possible improvement in the treatment of initial conditions here, code it up and make some preliminary assessment of its effectiveness. How will you decide if it is a substantial improvement?</p>
<p></p>
<p><a href="initial-values-exercise.html">Worked solution to the Exercise</a></p>
</section>
<section id="parameter-estimation-using-randomized-starting-values" class="level2">
<h2 class="anchored" data-anchor-id="parameter-estimation-using-randomized-starting-values">Parameter estimation using randomized starting values</h2>
<p>Think about possible improvements on the assignment of randomized starting values for the parameter estimation searches. Propose and try out a modification of the procedure. Does it make a difference?</p>
<p></p>
<p><a href="starting-values-exercise.html">Worked solution to the Exercise</a></p>
</section>
<section id="demography-and-discrete-time" class="level2">
<h2 class="anchored" data-anchor-id="demography-and-discrete-time">Demography and discrete time</h2>
<p>It can be surprisingly hard to include birth, death, immigration, emigration and aging into a disease model in satisfactory ways. Consider the strengths and weaknesses of the analysis presented, and list changes to the model that might be improvements.</p>
<p>In an imperfect world, it is nice to check the extent to which the conclusions are insensitive to alternative modeling decisions. These are testable hypotheses, which can be addressed within a plug-and-play inference framework. Identify what would have to be done to investigate the changes you have proposed. Optionally, you could have a go at coding something up to see if it makes a difference.</p>
<p></p>
<p><a href="demography-exercise.html">Worked solution to the Exercise</a></p>
</section>
<section id="diagnosing-filtering-and-maximization-convergence" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="diagnosing-filtering-and-maximization-convergence">Diagnosing filtering and maximization convergence</h2>
<p>Are there outliers in the data (i.e., observations that do not fit well with our model)? Are we using unnecessarily large amounts of computer time to get our results? Are there indications that we would should run our computations for longer? Or maybe with different choices of algorithmic settings? In particular, <code>cooling.fraction.50</code> gives the fraction by which the random walk standard deviation is decreased (“cooled”) in 50 iterations. If <code>cooling.fraction.50</code> is too small, the search will “freeze” too soon, evidenced by flat parallel lines in the convergence diagnostics. If <code>cooling.fraction.50</code> is too large, the researcher may run of of time, patience or computing budget (or all three) before the parameter trajectories approach an MLE. Use the diagnostic plots below, or other calculations, to address these issues.</p>
<p></p>
<p><a href="convergence-exercise.html">Worked solution to the Exercise</a></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>  best <span class="ot">&lt;-</span> m3[r3<span class="sc">$</span>logLik<span class="sc">&gt;</span><span class="fu">max</span>(r3<span class="sc">$</span>logLik)<span class="sc">-</span><span class="dv">10</span>]</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  best <span class="sc">|&gt;</span> <span class="fu">as.data.frame</span>() <span class="sc">|&gt;</span> <span class="fu">select</span>(time,.L1,ess,cond.logLik) <span class="sc">|&gt;</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pivot_longer</span>(<span class="sc">-</span><span class="fu">c</span>(.L1,time)) <span class="sc">|&gt;</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>time,<span class="at">y=</span>value,<span class="at">color=</span><span class="fu">factor</span>(.L1)))<span class="sc">+</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>()<span class="sc">+</span></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">guides</span>(<span class="at">color=</span><span class="st">"none"</span>)<span class="sc">+</span></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_grid</span>(name<span class="sc">~</span>.,<span class="at">scales=</span><span class="st">"free_y"</span>)<span class="sc">+</span></span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="tmp//figure/mif_diagnostics1-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-fig-pos="h!" width="2049"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>  best <span class="sc">|&gt;</span> <span class="fu">traces</span>() <span class="sc">|&gt;</span> <span class="fu">melt</span>() <span class="sc">|&gt;</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(<span class="sc">!</span>(name <span class="sc">%in%</span> fp_names)) <span class="ot">-&gt;</span> best_tr</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  best_tr <span class="sc">|&gt;</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>iteration,<span class="at">y=</span>value,<span class="at">color=</span><span class="fu">factor</span>(.L1)))<span class="sc">+</span></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>()<span class="sc">+</span></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">guides</span>(<span class="at">color=</span><span class="st">"none"</span>)<span class="sc">+</span></span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_wrap</span>(<span class="sc">~</span>name,<span class="at">scales=</span><span class="st">"free_y"</span>)<span class="sc">+</span></span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="tmp//figure/mif_diagnostics2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-fig-pos="h!" width="2049"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>The likelihood is particularly important to keep in mind. If parameter estimates are numerically unstable, that could be a consequence of a weakly identified parameter subspace.</li>
<li>The presence of some weakly identified combinations of parameters is not fundamentally a scientific flaw; rather, our scientific inquiry looks to investigate which questions can and cannot be answered in the context of a set of data and modeling assumptions.</li>
<li>As long as the search is demonstrably approaching the maximum likelihood region we should not necessarily be worried about the stability of parameter values (at least, from the point of diagnosing successful maximization).</li>
<li>So, we zoom in on the likelihood convergence plot:</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>  best_tr <span class="sc">|&gt;</span> <span class="fu">filter</span>(name<span class="sc">==</span><span class="st">"loglik"</span>) <span class="sc">|&gt;</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(value)) <span class="ot">-&gt;</span> logLik_trace</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  logLik_trace <span class="sc">|&gt;</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>iteration,<span class="at">y=</span>value,<span class="at">group=</span>.L1))<span class="sc">+</span></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="at">alpha=</span><span class="fl">0.15</span>)<span class="sc">+</span></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">lims</span>(<span class="at">y=</span><span class="fu">c</span>(<span class="fu">max</span>(logLik_trace<span class="sc">$</span>value)<span class="sc">-</span><span class="dv">10</span>,<span class="cn">NA</span>))<span class="sc">+</span></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">y=</span><span class="st">"logLik"</span>)<span class="sc">+</span></span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="tmp//figure/likelihood_convergence-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%" data-fig-pos="h!"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="references" class="level1">
<h1>References</h1>
<section id="references-1" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="references-1">References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-Martinez-Bakker2015" class="csl-entry" role="listitem">
Martinez-Bakker, Micaela, Aaron A. King, and Pejman Rohani. 2015. <span>“Unraveling the Transmission Ecology of Polio.”</span> <em>PLoS Biol</em> 13 (6): e1002172. <a href="https://doi.org/10.1371/journal.pbio.1002172">https://doi.org/10.1371/journal.pbio.1002172</a>.
</div>
</div>
</section>
<section id="acknowledgments-and-license" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="acknowledgments-and-license">Acknowledgments and License</h2>
<ul>
<li><p>This lesson is prepared for the <a href="https://kingaa.github.io/sbied/">Simulation-based Inference for Epidemiological Dynamics</a> module at the Summer Institute in Statistics and Modeling in Infectious Diseases, <a href="https://www.biostat.washington.edu/suminst/sismid">SISMID</a>.</p></li>
<li><p>The materials build on <a href="https://kingaa.github.io/sbied/acknowledge.html">previous versions of this course and related courses</a>.</p></li>
<li><p>Produced with R version 4.4.0 and pomp version 5.9.</p></li>
<li><p>Licensed under the <a href="https://creativecommons.org/licenses/by-nc/3.0/">Creative Commons attribution-noncommercial license</a>. Please share and remix noncommercially, mentioning its origin.</p>
<p></p></li>
</ul>
</section>
<section id="license-acknowledgments-and-links" class="level2 allowframebreaks">
<h2 class="allowframebreaks anchored" data-anchor-id="license-acknowledgments-and-links">License, acknowledgments, and links</h2>
<ul>
<li><p>This lesson is prepared for the <a href="https://kingaa.github.io/sbied/">Simulation-based Inference for Epidemiological Dynamics</a> module at the Summer Institute in Statistics and Modeling in Infectious Diseases, <a href="https://www.biostat.washington.edu/suminst/sismid">SISMID</a>.</p></li>
<li><p>The materials build on <a href="../acknowledge.html">previous versions of this course and related courses</a>.</p></li>
<li><p>Licensed under the <a href="https://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial license</a>. Please share and remix non-commercially, mentioning its origin. </p></li>
<li><p>Produced with R version 4.4.0 and pomp version 5.9.</p></li>
<li><p>Compiled on 2024-06-17.</p></li>
</ul>
<p><a href="index.html">Back to Lesson</a></p>
<p><a href="./main.R"><code>R</code> codes for this lesson</a></p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>