project:
  type: website

website:
  title: "EpiSim"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - instruction.qmd
      - introduction.qmd
      - simulation.qmd
      - likelihood.qmd
      - iterated.qmd
      - case study.qmd
      - metapop.qmd

editor: visual

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-in-header:
      text: |
        <script>
        MathJax = {
          loader: {
            load: ['[tex]/boldsymbol']
          },
          tex: {
            tags: "all",
            inlineMath: [['$','$'], ['\\(','\\)']],
            displayMath: [['$$','$$'], ['\\[','\\]']],
            processEscapes: true,
            processEnvironments: true,
            packages: {
              '[+]': ['boldsymbol']
            }
          }
        };
        </script>
        <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
