project:
  type: website

website:
  title: "EpiSim"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - instruction.qmd
      - introduction.qmd
      - simulation.qmd
      - likelihood.qmd
      - iterated.qmd
      - influenza.qmd
      - measles.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

