project:
  type: website
  render:
    - "*.qmd"
    - "!slides/"
    - "slides/!polio"
    - "slides/!ebola"
    - "slides/!measles"
    - "slides/!contacts"

website:
  title: "EpiSim"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: instruction.qmd
        text: Instruction
      - href: introduction.qmd
        text: Introduction
      - href: simulation.qmd
        text: Simulation
      - href: likelihood.qmd
        text: Likelihood
      - href: iterated.qmd
        text: Iterated filtering
      - href: Bayesian.qmd
        text: Bayesian
      - href: case study.qmd
        text: Case study

editor: visual

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-after-body:
        - _slides/_includes/supp_bottom.html
        - _slides/_includes/license.html
    include-in-header:
      text: |
        <script>
        MathJax = {
          loader: {
            load: ['[tex]/boldsymbol']
          },
          tex: {
            tags: "all",
            inlineMath: [['$','$'], ['\\(','\\)']],
            displayMath: [['$$','$$'], ['\\[','\\]']],
            processEscapes: true,
            processEnvironments: true,
            packages: {
              '[+]': ['boldsymbol']
            }
          }
        };
        </script>
        <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
