---
title: "Simulation-based Inference for Epidemiological Dynamics"
author: Qianying (Ruby) Lin, Spencer J. Fox, Zian (Larry) Zhuang
toc: true
format:
  html:
    embed-resources: true
    code-background: true
    include-after-body:
        - _slides/_includes/main_bottom.html
        - _slides/_includes/license.html
engine: knitr
---

## Module Description

This module introduces statistical inference techniques and computational methods for dynamic models of epidemiological systems. 
The course will explore deterministic and stochastic formulations of epidemiological dynamics and develop inference methods appropriate for a range of models. 
Special emphasis will be on exact and approximate likelihood as the key elements in parameter estimation, hypothesis testing, and model selection. 
Specifically, the course will cover sequential Monte Carlo and synthetic likelihood techniques. Students will learn to implement these in **R** to carry out maximum likelihood and Bayesian inference. 
Knowledge of the material in Module 1 is assumed. 
Students new to **R** should complete a [tutorial](https://kingaa.github.io/R_Tutorial/) before the module.

## Course objectives

1.  To introduce partially observed Markov process (POMP) models as tools for scientific investigation and public health policy.

2.  To give students the ability to formulate POMP models of their own.

3.  To teach efficient approaches for performing scientific inference using POMP models.

4.  To familiarize students with the **pomp** package.

5.  To give students opportunities to work with such inference methods.

6.  To provide documented examples for student re-use.

## Lessons

0.  [Instructions for preparing your laptop for the course exercises.](https://rubbislam.quarto.pub/episim/instruction.html)

1.  [Introduction: What is “Simulation-based Inference for Epidemiological Dynamics”? POMPs and pomp.](https://rubbislam.quarto.pub/episim/introduction.html)

2.  [Simulation of stochastic dynamic models.](https://rubbislam.quarto.pub/episim/simulation.html)

3.  [Likelihood for POMPs: theory and practice.](https://rubbislam.quarto.pub/episim/likelihood.html)

4.  [Iterated filtering: theory and practice.](https://rubbislam.quarto.pub/episim/iterated.html)

5.  [Bayesian statistics and PMCMC in pomp](https://rubbislam.quarto.pub/episim/Bayesian.html)

6.  [Case study: 1918 Spanish Flu in three cities of UK](https://rubbislam.quarto.pub/episim/case%20study.html)

7.  [Case study:](https://rubbislam.quarto.pub/episim/case%20study.html)

## Stochastic SIR simulator

For an interactive exploration of the stochastic SIR model, you can access the dedicated [shiny app](https://spncrfx.shinyapps.io/stochastic-sir/) developed for this course. 
This application allows you to simulate and analyze the dynamics of disease spread using the stochastic SIR framework.

## Acknowledgements

This website and all the materials are adapted from <https://kingaa.github.io/sbied/>. 
We would like to send our sincere gratitude to Professors [Aaron A. King](https://kinglab.eeb.lsa.umich.edu/king) and [Edward L. Ionides](https://dept.stat.lsa.umich.edu/~ionides/) for creating this wonderful course and for helping us developing our own version.
